[versions]
composeGradlePlugin = "1.6.10"
jvm-target = "17"
agp = "8.2.2"
android-compileSdk = "34"
android-minSdk = "29"
android-targetSdk = "34"
androidx-activityCompose = "1.9.0"
androidx-appcompat = "1.7.0"
androidx-constraintlayout = "2.1.4"
androidx-core-ktx = "1.13.1"
androidx-espresso-core = "3.5.1"
androidx-material = "1.12.0"
androidx-test-junit = "1.1.5"
compose = "1.6.7"
compose-plugin = "1.6.10"
junit = "4.13.2"
kotlin = "2.0.0"
ktor = "2.3.11"
kotlinx-serialization-json = "1.7.0"
compose-navigation = "2.7.0-alpha03"
gson = "2.10.1"
lifecycleViewmodelCompose = "2.8.0"
pluto = "2.2.2"
coroutine = "1.9.0-RC"
generativeai = "0.7.0"

[libraries]
compose-gradle-plugin = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "composeGradlePlugin" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "androidx-material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-ios = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }

compose-navigation = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "compose-navigation" }

#coroutine
coroutine-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutine" }
coroutine-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutine" }
coroutine-core-iosarm64 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-iosarm64", version.ref = "coroutine" }
coroutine-core-iossimulatorarm64 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-iossimulatorarm64", version.ref = "coroutine" }
coroutine-core-js = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-js", version.ref = "coroutine" }

# pluto
lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
pluto = { module = "com.plutolib:pluto", version.ref = "pluto" }
pluto-no-op = { module = "com.plutolib:pluto-no-op", version.ref = "pluto" }
pluto-bundle-core = { module = "com.plutolib.plugins:bundle-core", version.ref = "pluto" }
pluto-bundle-core-no-op = { module = "com.plutolib.plugins:bundle-core-no-op", version.ref = "pluto" }
pluto-plugin-network = { module = "com.plutolib.plugins:network", version.ref = "pluto" }
pluto-plugin-network-no-op = { module = "com.plutolib.plugins:network-no-op", version.ref = "pluto" }
pluto-plugin-network-ktor-interceptor = { module = "com.plutolib.plugins:network-interceptor-ktor", version.ref = "pluto" }
pluto-plugin-network-ktor-interceptor-no-op = { module = "com.plutolib.plugins:network-interceptor-ktor-no-op", version.ref = "pluto" }
pluto-plugin-logger = { module = "com.plutolib.plugins:logger", version.ref = "pluto" }
pluto-plugin-logger-no-op = { module = "com.plutolib.plugins:logger-no-op", version.ref = "pluto" }
pluto-plugin-shared-preference = { module = "com.plutolib.plugins:preferences", version.ref = "pluto" }
pluto-plugin-shared-preference-no-op = { module = "com.plutolib.plugins:preferences-no-op", version.ref = "pluto" }
pluto-plugin-exception = { module = "com.plutolib.plugins:exceptions", version.ref = "pluto" }
pluto-plugin-exception-no-op = { module = "com.plutolib.plugins:exceptions-no-op", version.ref = "pluto" }
pluto-plugin-room = { module = "com.plutolib.plugins:rooms-db", version.ref = "pluto" }
pluto-plugin-room-no-op = { module = "com.plutolib.plugins:rooms-db-no-op", version.ref = "pluto" }
pluto-plugin-data-store = { module = "com.plutolib.plugins:datastore-pref", version.ref = "pluto" }
pluto-plugin-data-store-no-op = { module = "com.plutolib.plugins:datastore-pref-no-op", version.ref = "pluto" }
generativeai = { group = "com.google.ai.client.generativeai", name = "generativeai", version.ref = "generativeai" }

[bundles]
pluto = ["pluto", "pluto-bundle-core", "pluto-plugin-network", "pluto-plugin-network-ktor-interceptor", "pluto-plugin-logger", "pluto-plugin-shared-preference", "pluto-plugin-exception", "pluto-plugin-room", "pluto-plugin-data-store"]
pluto-no-op = ["pluto-no-op", "pluto-bundle-core-no-op", "pluto-plugin-network-no-op", "pluto-plugin-network-ktor-interceptor-no-op", "pluto-plugin-logger-no-op", "pluto-plugin-shared-preference-no-op", "pluto-plugin-exception-no-op", "pluto-plugin-room-no-op", "pluto-plugin-data-store-no-op"]

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }