[versions]
android-activity-compose = "1.8.2"
android-compose-ui = "1.6.2"
android-navigation-compose = "2.7.7"

junit = "4.13.2"
android-junit = "1.1.5"

android-core-ktx = "1.12.0"
android-espresso-core = "3.5.1"
android-appcompat = "1.6.1"
android-material = "1.11.0"

kotlinx-serialization-json = "1.6.3"

ktor = "2.3.8"

android-lifecycle-runtime-ktx = "2.7.0"

android-material3 = "1.2.0"

android-pluto = "2.2.1"

coroutine = "1.8.0"
android-coroutine = "1.7.3"

android-lifecycle-viewmodel-compose = "2.7.0"

android-gradle-plugin = "8.3.0"
kotlin = "1.9.22"
org-jetbrains-kotlin-jvm = "1.9.22"


[libraries]
android-core-ktx = { module = "androidx.core:core-ktx", version.ref = "android-core-ktx" }

android-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "android-activity-compose" }

android-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "android-espresso-core" }

junit = { module = "junit:junit", version.ref = "junit" }
android-ext-junit = { module = "androidx.test.ext:junit", version.ref = "android-junit" }

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ios-ktor-client = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }

android-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "android-lifecycle-runtime-ktx" }
android-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "android-material3" }

android-pluto-plugins-bundle-core = { module = "com.plutolib.plugins:bundle-core", version.ref = "android-pluto" }
android-pluto-plugins-bundle-core-no-op = { module = "com.plutolib.plugins:bundle-core-no-op", version.ref = "android-pluto" }
android-pluto = { module = "com.plutolib:pluto", version.ref = "android-pluto" }
android-pluto-no-op = { module = "com.plutolib:pluto-no-op", version.ref = "android-pluto" }

android-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "android-compose-ui" }
android-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "android-compose-ui" }
android-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "android-compose-ui" }
android-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "android-compose-ui" }
android-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "android-compose-ui" }
android-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "android-compose-ui" }

android-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "android-appcompat" }
android-material = { group = "com.google.android.material", name = "material", version.ref = "android-material" }
android-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "android-lifecycle-viewmodel-compose" }
android-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "android-navigation-compose" }

coroutine = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutine" }
android-coroutine = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "android-coroutine" }

[bundles]

[plugins]